[package]
name = "miss-edwards-kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
uefi = { version = "0.36.1", features = ["logger", "panic_handler"] }
log = "0.4"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
